"""Initial Migration 2

Revision ID: 57153789a80e
Revises: c5420be5e464
Create Date: 2025-03-25 16:30:40.884863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57153789a80e'
down_revision: Union[str, None] = 'c5420be5e464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_tree_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['users_tree_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('person_id_1', sa.Integer(), nullable=True),
    sa.Column('person_id_2', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.Enum('MOTHER', 'FATHER', 'DAUGHTER', 'SON', 'BROTHER', 'SISTER', 'HUSBAND', 'WIFE', 'GRANDMOTHER', 'GRANDFATHER', 'RELATIVE', name='relationtype'), nullable=False),
    sa.ForeignKeyConstraint(['person_id_1'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['person_id_2'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('persons', sa.Column('tree_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'persons', 'trees', ['tree_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='foreignkey')
    op.drop_column('persons', 'tree_id')
    op.drop_table('relationships')
    op.drop_table('trees')
    op.drop_table('users')
    # ### end Alembic commands ###
