"""update models persons (make column sex mandatory)

Revision ID: dc7962e5b7f5
Revises: d8cd947b9102
Create Date: 2025-04-22 14:16:24.525470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7962e5b7f5'
down_revision: Union[str, None] = 'd8cd947b9102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'sex',
               existing_type=postgresql.ENUM('FEMALE', 'MALE', name='sex_of_person'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'sex',
               existing_type=postgresql.ENUM('FEMALE', 'MALE', name='sex_of_person'),
               nullable=True)
    # ### end Alembic commands ###
